command! EhelperToggleOutput call ehelper#ToggleOutputWindow()
command! EhelperCompile call ehelper#Compile()
command! EhelperCompileRun call ehelper#CompileRun()
command! EhelperCompileRunTestCases call ehelper#CompileRunTestCases()
command! EhelperRun call ehelper#Run()
command! EhelperRunTestCases call ehelper#ExecuteProgram()
